version: '3'

services:
  mlflow:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./mlruns:/app/mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5001
      - MLFLOW_S3_ENDPOINT_URL=https://storage.yandexcloud.net
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - MLFLOW_S3_BUCKET=${MLFLOW_S3_BUCKET}
      - MLFLOW_ARTIFACT_ROOT=s3://${MLFLOW_S3_BUCKET}/mlflow
      - MLFLOW_S3_IGNORE_TLS=true
    networks:
      - mlflow-network

networks:
  mlflow-network:
    driver: bridge 